### ISSUE TITLE
The `bundle.yaml` file does not contain all required namespaces

### ISSUE THREAD

**Issue by MathyV** [scaleway/cert-manager-webhook-scaleway#24]
**Describe the bug**
Deployment with `bundle.yaml` will fail because the `Certificate` is in a different namespace (`cert-manager`) than the pod (`default`) so the generated secret is not accessible.

**To Reproduce**
Try to deploy `bundle.yaml`

**Expected behavior**
It should deploy

**Details (please complete the following information):**
 - Scaleway Cert Manager Webhook version: v0.1.0
 - Platform: ? 
 - Kubernetes version: 1.29.1

**Additional context**
This patch fixes it by making sure everything is deployed in the `cert-manager` namespace:
```
--- bundle.yaml 2024-05-08 19:23:13.076578543 +0200
+++ scaleway-webhook.yaml       2024-05-08 19:15:09.796100765 +0200
@@ -3,6 +3,7 @@
 kind: ServiceAccount
 metadata:
   name: scaleway-certmanager-webhook
+  namespace: cert-manager
   labels:
     app: scaleway-certmanager-webhook
 ---
@@ -11,6 +12,7 @@
 kind: ClusterRole
 metadata:
   name: scaleway-certmanager-webhook:domain-solver
+  namespace: cert-manager
   labels:
     app: scaleway-certmanager-webhook
 rules:
@@ -27,6 +29,7 @@
 kind: ClusterRoleBinding
 metadata:
   name: scaleway-certmanager-webhook:auth-delegator
+  namespace: cert-manager
   labels:
     app: scaleway-certmanager-webhook
 roleRef:
@@ -43,6 +46,7 @@
 kind: ClusterRoleBinding
 metadata:
   name: scaleway-certmanager-webhook:domain-solver
+  namespace: cert-manager
   labels:
     app: scaleway-certmanager-webhook
 roleRef:
@@ -113,6 +117,7 @@
 kind: Service
 metadata:
   name: scaleway-certmanager-webhook
+  namespace: cert-manager
   labels:
     app: scaleway-certmanager-webhook
 spec:
@@ -129,6 +134,7 @@
 kind: Deployment
 metadata:
   name: scaleway-certmanager-webhook
+  namespace: cert-manager
   labels:
     app: scaleway-certmanager-webhook
 spec:
@@ -183,6 +189,7 @@
 kind: APIService
 metadata:
   name: v1alpha1.acme.scaleway.com
+  namespace: cert-manager
   labels:
     app: scaleway-certmanager-webhook
   annotations:
```
